context:
  name: airflow-pydantic
  version: "1.2.4"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-pydantic/airflow_pydantic-${{ version }}.tar.gz
  sha256: f63e9b4b669e2d409207130fadc5532b1931d8fb675ab628297ea682e481cf08

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.8,<3
    - pkn >=0.1.3
    - pydantic >=2

tests:
  - python:
      imports:
        - airflow_pydantic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Pydantic models for Apache Airflow
  homepage: https://github.com/airflow-laminar/airflow-pydantic
  repository: https://github.com/airflow-laminar/airflow-pydantic

extra:
  recipe-maintainers:
    - timkpaine
